#!/usr/bin/env python3
"""
Build a single-file version of spark-query-analyzer.

Each module is inlined verbatim.  Internal 'from spark_query_analyzer.X import'
and 'import spark_query_analyzer' statements are stripped (since everything
is now in a single namespace).  All other top-level imports are kept.

Usage:
    python3 scripts/build_single_file.py
"""

import os, re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO_ROOT, "spark_query_analyzer_single.py")

# Order matters — magic.py and __init__.py go last.
MODULES = [
    "spark_query_analyzer/analyzer.py",
    "spark_query_analyzer/display_utils.py",
    "spark_query_analyzer/narrative_explainer.py",
    "spark_query_analyzer/cluster_advisor.py",
    "spark_query_analyzer/report_exporter.py",
    "spark_query_analyzer/post_execution_analyser.py",
    "spark_query_analyzer/aqe_checker.py",
    "spark_query_analyzer/python_scanner.py",
    "spark_query_analyzer/stats_checker.py",
    "spark_query_analyzer/streaming_analyser.py",
    "spark_query_analyzer/delta_analyser.py",
    "spark_query_analyzer/cost_estimator.py",
    "spark_query_analyzer/cross_query_optimiser.py",
    "spark_query_analyzer/history_tracker.py",
    "spark_query_analyzer/performance_monitor.py",
    "spark_query_analyzer/system_info.py",
    "spark_query_analyzer/magic.py",
    "spark_query_analyzer/__init__.py",
]


def is_internal_import(line: str) -> bool:
    """True for 'from spark_query_analyzer.X import' or 'import spark_query_analyzer'."""
    stripped = line.strip()
    return (
        stripped.startswith("from spark_query_analyzer")
        or stripped.startswith("import spark_query_analyzer")
    )


def top_level_imports(content: str) -> list[str]:
    """
    Return all non-indented top-level import lines from a module.
    Skips:
      - Internal spark_query_analyzer imports
      - Indented continuation lines inside multiline imports
    """
    lines = content.split("\n")
    result = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        # Must start at column 0 (not indented) to be a top-level import
        if line[0] in (" ", "\t"):
            continue
        if stripped.startswith("import ") or stripped.startswith("from "):
            if not is_internal_import(line):
                result.append(line)
    return result


BOOTSTRAP = r'''#!/usr/bin/env python3
"""
spark-query-analyzer — single-file version
https://github.com/eddalmond/spark-query-analyzer

Paste this entire file into a Databricks notebook cell and run it ONCE per session
to register the %analyze and %%analyze_batch magics.

Usage (in your setup cell — once per session):
    exec(open("/tmp/spark_query_analyzer_single.py").read())

Then in any SQL cell:
    %analyze
    SELECT ...

Flags:
    %analyze --dry-run            plan-only analysis (default)
    %analyze --execute            run query + post-execution skew (F-03)
    %analyze --export <path>      save HTML report to DBFS/mounted storage (F-14)

---
Auto-generated by scripts/build_single_file.py. Do not edit manually.
"""

import sys as _sys, os as _os
_this_dir = _os.path.dirname(_os.path.abspath(__file__))
if _this_dir not in _sys.path:
    _sys.path.insert(0, _this_dir)
'''

DIVIDER = "\n# ════════════════════════════════════════════════════════════════\n"


def process_module(path: str) -> str:
    """Read module, strip internal imports, return clean code."""
    with open(path) as f:
        content = f.read()

    # Collect top-level external imports
    imports = top_level_imports(content)
    import_block = "\n".join(imports) + "\n" if imports else ""

    # Strip all lines containing internal spark_query_analyzer imports
    lines = content.split("\n")
    clean_lines = []
    for line in lines:
        # Remove lines that are ONLY an internal import (possibly aliased)
        stripped = line.strip()
        # Multi-line from spark_query_analyzer import (...) — remove continuation lines too
        if is_internal_import(stripped):
            continue
        clean_lines.append(line)

    return import_block + "\n".join(clean_lines)


def build() -> str:
    output = BOOTSTRAP + DIVIDER

    for module_path in MODULES:
        full_path = os.path.join(REPO_ROOT, module_path)
        if not os.path.exists(full_path):
            print(f"  ⚠️  Skipping: {module_path} (not found)")
            continue

        module_name = module_path.split("/")[-1]
        print(f"  + {module_name}")

        code = process_module(full_path)
        output += f"# ── {module_name} ──────────────────────────────────────────────────{DIVIDER}"
        output += code + "\n"

    return output


if __name__ == "__main__":
    print("Building single-file spark-query-analyzer...\n")
    result = build()
    with open(OUT_PATH, "w") as f:
        f.write(result)
    lines = result.count("\n")
    kb = len(result.encode()) // 1024
    print(f"\n  → {OUT_PATH}")
    print(f"  → {lines} lines, ~{kb}KB")

    # Smoke tests
    checks = {
        "run_analysis": "Core function",
        "NarrativeExplainer": "F-10 NL Summary",
        "ClusterRecommendation": "F-12 Cluster Advisor",
        "export_report": "F-14 HTML Export",
        "build_spark_ui_link": "F-15 Spark UI Links",
        "SkewFinding": "Skew finding dataclass",
        "register_analyze_magic": "Magic registration",
        "from mlflow.deployments import": "MLflow optional path",
        "dbutils": "DBFS export path",
    }
    print()
    all_ok = True
    for sym, desc in checks.items():
        found = sym in result
        status = "✅" if found else "❌"
        print(f"  {status} {desc}: {sym}")
        if not found:
            all_ok = False
    print(f"\n  {'✅ All checks passed' if all_ok else '❌ Some checks failed'}")
    print("  Done ✅")